<?php

return [
    'keywords' => [
        "laravel",
        "framework",
        "atannex",
        "lebialem",
        "fontem",
        "alou",
        "wabane",
        "lewoh",
        "ndungated",
        "nwametaw",
        "nwangong",
        "m'mouck-mbie",
        "m'mouck-ngie",
        "lebang",
        "essoh-attah",
        "njogwi",
        "bamumbu",
        "bangang",
        "banti",
        "bechati",
        "besali",
        "folepi",
        "igumbo",
        "nkong",
    ],
];
